### ISSUE TITLE
Zadávání poloměru Země může skončit s chybou

### ISSUE THREAD

**Issue by xtompok** [matyasm1995/uvod_do_prg#1]
První zadání poloměru je ošetřeno korektně pomocí try - except, ale pokud v rámci exceptu opět zadám nečíselný poloměr, tak to spadne na ValueError. Řešení je buď hned napoprvé skončit s chybou, nebo dát zadávání poloměru do cyklu.

**Comment by matyasm1995** [comment]
vyreseno
