### ISSUE TITLE
Funkce graphic je pochybná

### ISSUE THREAD

**Issue by xtompok** [matyasm1995/uvod_do_prg#22]
- nerozumím tomu, co dělá první while
- nešlo by druhý cyklus udělat jako `for` přes `lat`?
- `xi = x / ((i - 1) / 2)` není díky nevhodně pojmenovaným proměnným jasné, co dělá a proč
- `for i in range(i):` je extrémně nevhodná konstrukce. Parametr funkce by se neměl jmenovat `i`, protože se toto písmeno právě často používá v cyklech jako iterační proměnná, takto o jeho hodnotu v cyklu přijdu
- lépe než kontrolovat, zda je aktuální bod v `point_g` validní je vkládat to point_g pouze validní body už při výpočtu

Funkci doporučuji celou přepsat, ne proto, že by nefungovala, ale proto, že pokud ji napíšeš celou znovu od začátku, tak se snáze vyvaruješ nevhodných konstrukcí, kterých je funkce plná

**Comment by matyasm1995** [comment]
Značně zjednodušeno
