### ISSUE TITLE
Načítání čísel je vhodné mít v samostatné funkci

### ISSUE THREAD

**Issue by xtompok** [matyasm1995/uvod_do_prg#5]
V kódu se na mnoha místech načítá číslo a následně se kontrolují jeho vlastnosti. Lépe oddělit do samostatné funkce, která dostane řetězec, který má vypsat a případné podmínky na číslo a vrátí číslo až po úspěšném zadání.

**Comment by matyasm1995** [comment]
snad by mělo být vyřešeno
